spring:
  #настройка thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    banner-mode: off

  datasource:
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}?createDatabaseIfNotExist=true
    username: ${spring.datasource.username}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    drop-first: true




